# Generated by Django 3.0.10 on 2025-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='image',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300?text=No+Image+Available'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
