# Generated by Django 3.0.10 on 2025-01-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tvshow_favorite_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
